### ISSUE TITLE
Implement `std::marker::Send` for SearchResults

### ISSUE THREAD

**Issue by jackpeters667** [meilisearch/meilisearch-rust#577]
**Description**
I'm trying to update my application following the new changes where we can use custom http clients following https://github.com/meilisearch/meilisearch-rust/pull/524#issuecomment-2056865261

```rust
struct MyStruct {
    value: String
}
```

```toml
[dependencies]
meilisearch-sdk = "0.26.0"

[patch.crates-io]
meilisearch-sdk = { git = "https://github.com/meilisearch/meilisearch-rust", rev = "043a553" }

```

When I try to compile:
```
dyn futures_util::Future<Output = Result<SearchResults<MyStruct>, meilisearch_sdk::errors::Error>>` cannot be sent between threads safely
```
